import { icons } from "lucide-svelte";
import { Description } from "./components/ui/card";

const contenu : any = {
  fr : {
    welcome: "Bienvenue",
    login: "Se connecter",
    board:"Tableau de bord",
    logout: "Se déconnecter",
    optional: "Optionel",
    service: "Service",
    selectService: "Sélectionnez votre service",
    chooseService: "Choisissez un service",
    totalPrice: "Prix total",
    Convoyage: {
      name : "Convoyage",
      title : "Votre véhicule, notre route",
      description : "Transport point A → point B partout en France et en Europe, assuré par un professionnel du convoyage pour une prise en charge sécurisée et fiable.",
    },
    Remorquage:{
      name : "Remorquage",
      title:"Votre véhicule, notre route",
      description: "Transport sécurisé de votre véhicule jusqu'à un garage partenaire ou l'adresse de votre choix."
    },
    Dépannage :{
      name: "Dépannage",
      title:"Votre véhicule, notre route",
      description: ["Dépannage sur place : Intervention rapide pour les pannes mécaniques courantes.",
          "Dépannage d'essence : Livraison de carburant sur place en cas de panne sèche.",
       "Dépannage électrique : Assistance immédiate avec un booster de batterie ou une station VE portative pour véhicules électriques."]
    },
    subtitle : "Prise en charge de véhicule sur mesure",
    why_choose_us : "Pourquoi nous choisir ?",
    reserve : "Réserver",
    offersTitle: "Nos offres",
    deliveryDescription: "Livraison sur mesure dans toute l'Europe",
    flexibility: "Flexibilité maximale",
    flexibilityDescription: "Du sur-mesure pour chaque trajet. Nous adaptons nos services à vos besoins spécifiques, que ce soit pour le type de véhicule, le timing ou les exigences particulières.",
    security: "Sécurité garantie",
    securityDescription: "Chauffeurs expérimentés et véhicules adaptés. Nos professionnels sont formés pour manipuler tous types de véhicules, et notre flotte est équipée des dernières technologies de sécurité.",
    qualityPrice: "Rapport qualité-prix imbattable",
    qualityPriceDescription: "Des tarifs compétitifs pour un service premium. Nous offrons une transparence totale sur nos prix, sans frais cachés, tout en maintenant un niveau de service exceptionnel.",
    peaceOfMind: "Sérénité totale",
    peaceOfMindDescription: "Un paiement différé, vous ne payez que quand votre véhicule est arrivé à destination. Cette politique de paiement vous assure une tranquillité d'esprit tout au long du processus de livraison.",
    departLocation: "Lieux de départ (France)",
    arrivalLocation: "Lieux d'arrivée",
    vehicleType: "Type de véhicule",
    citadine: "Citadine",
    moto: "Moto",
    camion: "Camion",
    comment: "Commentaire",
    contact: "Contact",
    needMorePreciseAddress: "Besoin d'une adresse plus précise, avec une rue.",
    vehicleTypes :['Moto', 'Citadine', 'Sport', 'Berline', 'VUS', 'Fourgonnette', 'Camion (<3.5t)', 'Camion (>3.5t)'],
    vehicle: "Véhicule",
    makeAndModel: "Marque et modèle",
    numberPlate: "Immatriculation",
    seatingCapacity: "Capacité d'accueil",
    gearbox: "Boite de vitesse",
    piloteExpress: {
      title: "1. Le Pilote Express",
      description: "Un chauffeur professionnel prend le volant de votre véhicule pour une livraison en conduite directe. Idéal pour une livraison rapide et personnalisée.",
      features: [
        "Livraison porte-à-porte",
        "Chauffeurs expérimentés et certifiés"
      ]
    },
    coconRoulant: {
      title: "2. Le Cocon Roulant",
      description: "Votre véhicule voyage confortablement dans un camion spécialisé, préservant son kilométrage et son état. Parfait pour les véhicules de luxe ou de collection.",
      features: [
        "Protection maximale contre les intempéries",
        "Transport multi-véhicules possible"
      ]
    },
    card1Title: "Flexibilité maximale",
    card1Description: "Du sur-mesure pour chaque trajet. Nous adaptons nos services à vos besoins spécifiques, que ce soit pour le type de véhicule, le timing ou les exigences particulières.",
    card2Title: "Sécurité garantie",
    card2Description: "Chauffeurs expérimentés et véhicules adaptés. Nos professionnels sont formés pour manipuler tous types de véhicules, et notre flotte est équipée des dernières technologies de sécurité.",
    card3Title: "Rapport qualité-prix imbattable",
    card3Description: "Des tarifs compétitifs pour un service premium. Nous offrons une transparence totale sur nos prix, sans frais cachés, tout en maintenant un niveau de service exceptionnel.",
    card4Title: "Sérénité totale",
    card4Description: "Un paiement différé, vous ne payez que quand votre véhicule est arrivé à destination. Cette politique de paiement vous assure une tranquillité d'esprit tout au long du processus de livraison.",
    footer : "Faites confiance à AMSTRAM pour le transport de votre véhicule et vivez une expérience de livraison sans précédent !",
    terms : "Conditions Générales",
    privacy : "Politique de Confidentialité",
    phone : "Téléphone",
    telephone: "Telephone",
    phoneNumber: "Numéro de téléphone commence par + (+337 ou +336)",
    enterPhoneNumber: "Entrez votre numéro de téléphone",
    vehiculeAvailability: "Disponibilité du véhicule",
    collectionNoEarlierThan: "Collecte pas avant",
    deliveryUntilHelp: "La date de collection doit être au moins 3 jours après la date de collection",
    deliveryUntil: "Livraison jusqu'au",
    collectionNoEarlierThanHelp: "La date de collecte doit être au moins à 24h d'aujourd'hui",
    availabilityDescription: "Plus la période d'utilisation est longue, plus votre demande sera priorisée",
    addContact: "Ajouter un contact",
    cancel: "Annuler",
    addNewContact: "Ajouter un nouveau contact",
    selectContact: "Sélectionner un contact",
    commentsDriver: "Commentaire pour le chauffeur",
    myRoutes: "Mes courses",
    verifyEmail: "Vérification de l'email",
    depannage_type: "Type de Dépannage",
    depannage: [
      { name: "Dépannage", icon: "Wrench" },
      { name: "Essence", icon: "Fuel" },
      { name: "Électrique", icon: "PlugZap" },
      {name : "Vidange" , icon: "Droplets"}
    ],
    // Nouvelles traductions pour la page de détails de route
    ownerContact: "Contact propriétaire",
    departure: "Départ",
    arrival: "Arrivée",
    availability: "Disponibilité",
    vehicleDetails: "Détails du véhicule",
    price: "Prix",
    status: "Statut",
    type: "Type",
    make: "Marque",
    licensePlate: "Plaque d'immatriculation",
    capacity: "Capacité",
    transmission: "Transmission",
    payNow: "PAYER MAINTENANT",
    paymentSuccess: "Paiement effectué avec succès",
    loading: "Chargement des informations du trajet...",
    detail:"Voir detail",
    calculatingPrice: "Calcul en cours...",
    calculatingPriceMessage: "Nous calculons le meilleur tarif pour votre trajet.",
    phoneVerification: "Vérification du téléphone",
    titleVerified: "Numéro vérifié",
    enterCode: "Entrez le code que vous avez reçu par SMS",
    sendCode: "Envoyer le code",
    verifyNumber: "Vérifier le numéro",
    verifyCode: "Vérifier le code",
    smsSentTo: "SMS envoyé à",
    resendCode: "Renvoyer le code",
    phoneNumberFormat: "Le numéro de téléphone doit commencer par un +.",
    invalidPhoneNumber: "Numéro de téléphone invalide, veuillez réessayer",
    phoneUpdateError: "Erreur lors de la mise à jour du numéro, veuillez réessayer",
    incorrectCodeError: "Code incorrect, veuillez réessayer",
    verificationError: "Erreur lors de la vérification du numéro, veuillez réessayer",
    enterMakeAndModel: "Entrez la marque et le modèle...",
   enterNumberPlate: "AA-123-AA",
    seats: "places",
    enterAdditionalComments: "Entrez des commentaires supplémentaires...",
    manual: "Manuelle",
    automatic: "Automatique",
   "semi-automatic": "Semi-automatique",
    cvt: "CVT (transmission à variation continue)",
    valid: "Validez",
  },
  en : {
    welcome: "Welcome",
    login: "Login",
    board:"Dashboard",
    service: "Service",
    logout: "Logout",
    optional: "Optional",
    selectService: "Select Your Service",
    chooseService: "Choose a service",
    totalPrice: "Total Price",
    title : "Your vehicle, our route",
    subtitle : "Custom delivery across Europe",
    why_choose_us : "Why choose us ?",
    reserve : "Reserve",
    offersTitle: "Our Offers",
    deliveryDescription: "Custom delivery across Europe",
    flexibility: "Maximum flexibility",
    flexibilityDescription: "Tailored for each trip. We adapt our services to your specific needs, whether it's for the type of vehicle, timing, or special requirements.",
    security: "Guaranteed security",
    securityDescription: "Experienced drivers and suitable vehicles. Our professionals are trained to handle all types of vehicles, and our fleet is equipped with the latest safety technologies.",
    qualityPrice: "Unbeatable value for money",
    qualityPriceDescription: "Competitive rates for premium service. We offer complete transparency on our prices, with no hidden fees, while maintaining an exceptional level of service.",
    peaceOfMind: "Total peace of mind",
    peaceOfMindDescription: "Deferred payment, you only pay when your vehicle has arrived at its destination. This payment policy ensures you peace of mind throughout the delivery process.",
    departLocation: "Departure (France)",
    arrivalLocation: "Arrival Locations",
    vehicle: "Vehicle",
    vehicleType: "Vehicle Type",
    citadine: "City car",
    moto: "Motorbike",
    camion: "Truck",
    comment: "Comment",
    needMorePreciseAddress: "Need a more precise address, with a street.",
    contact: "Contact",
    makeAndModel: "Make and Model",
    numberPlate: "Number Plate",
    seatingCapacity: "Seating Capacity",
    gearbox: "Gearbox",
    piloteExpress: {
      title: "1. The Express Driver",
      description: "A professional driver takes the wheel of your vehicle for direct delivery. Ideal for fast and personalized delivery.",
      features: [
        "Door-to-door delivery",
        "Experienced and certified drivers"
      ]
    },
    coconRoulant: {
      title: "2. The Rolling Cocoon",
      description: "Your vehicle travels comfortably in a specialized truck, preserving its mileage and condition. Perfect for luxury or collectible vehicles.",
      features: [
        "Maximum protection against the elements",
        "Multi-vehicle transport possible"
      ]
    },
    card1Title: "Maximum flexibility",
    card1Description: "Tailored for each trip. We adapt our services to your specific needs, whether it's for the type of vehicle, timing, or special requirements.",
    card2Title: "Guaranteed security",
    card2Description: "Experienced drivers and suitable vehicles. Our professionals are trained to handle all types of vehicles, and our fleet is equipped with the latest safety technologies.",
    card3Title: "Unbeatable value for money",
    card3Description: "Competitive rates for premium service. We offer complete transparency on our prices, with no hidden fees, while maintaining an exceptional level of service.",
    card4Title: "Total peace of mind",
    card4Description: "Deferred payment, you only pay when your vehicle has arrived at its destination. This payment policy ensures you peace of mind throughout the delivery process.",
    footer : "Trust AMSTRAM for the transport of your vehicle and enjoy a delivery experience like no other!",
    terms :"Terms and Conditions",
    privacy : "Privacy Policy",
    phone : "Phone",
    telephone: "Telephone",
    phoneNumber: "Phone number starts with + (+337 or +336)",
    enterPhoneNumber: "Enter your phone number",
    vehicleTypes :['Motorcycle', 'City car', 'Sports', 'Sedan', 'SUV', 'Van', 'Truck (<3.5t)', 'Truck (>3.5t)'],
    vehiculeAvailability: "Vehicle availability",
    collectionNoEarlierThan: "Collection no earlier than",
    deliveryUntil: "Delivery no later than",
    availabilityDescription: "The greater the availability period, the quicker we'll find you a driver",
    addContact: "Add a contact",
    cancel: "Cancel",
    addNewContact: "Add a new contact",
    selectContact: "Select a contact",
    deliveryUntilHelp: "The collection date must be at least 3 days after the collection date",
    collectionNoEarlierThanHelp : "The collection date must be at least the next day",
    commentsDriver: "Comment for the driver?",
    myRoutes: "My routes",
    verifyEmail: "Email verification",
    Convoyage: {
      name: "Convoy",
      title: "Your vehicle, our route",
      description: "Transport from point A → point B throughout France and Europe, provided by a professional driver for secure and reliable handling.",
    },
    Remorquage: {
      name: "Towing",
      title: "Your vehicle, our route",
      description: "Secure transport of your vehicle to a partner garage or address of your choice."
    },
    "Dépannage": {
      name: "Breakdown Service",
      title: "Your vehicle, our route",
      description: ["On-site breakdown assistance: Rapid intervention for common mechanical failures.",
          "Fuel breakdown assistance: On-site fuel delivery in case of running out of gas.",
          "Electrical breakdown assistance: Immediate assistance with a battery booster or portable EV station for electric vehicles."]
    },
    depannage_type: "Type of Breakdown",
    depannage: [
      { name: "Mechanical", icon: "Wrench" },
      { name: "Fuel", icon: "Fuel" },
      { name: "Electrical", icon: "PlugZap" },
      {name :"Emptying" ,icon : "Droplets"}
    ],
    description1: "Whether you're a private individual or a business, AMSTRAM offers a vehicle transport solution tailored to your needs.",
    ownerContact: "Owner Contact",
    departure: "Departure",
    arrival: "Arrival",
    availability: "Availability",
    vehicleDetails: "Vehicle Details",
    price: "Price",
    status: "Status",
    type: "Type",
    make: "Make",
    licensePlate: "License Plate",
    capacity: "Capacity",
    transmission: "Transmission",
    payNow: "PAY NOW",
    paymentSuccess: "Payment successfully completed",
    loading: "Loading route information...",
    detail: "See detail",
    calculatingPrice: "Calculating...",
    calculatingPriceMessage: "We're calculating the best price for your journey.",
    phoneVerification: "Phone verification",
    titleVerified: "Number verified",
    enterCode: "Enter the code you received by SMS",
    sendCode: "Send code",
    verifyNumber: "Verify number",
    verifyCode: "Verify code",
    smsSentTo: "SMS sent to",
    resendCode: "Resend code",
    phoneNumberFormat: "Phone number must start with +.",
    invalidPhoneNumber: "Invalid phone number, please try again",
    phoneUpdateError: "Error updating phone number, please try again",
    incorrectCodeError: "Incorrect code, please try again",
    verificationError: "Error verifying phone number, please try again",
    enterMakeAndModel: "Enter make and model...",
    enterNumberPlate: "AA-123-AA",
    seats: "seats",
    enterAdditionalComments: "Enter any additional comments...",
    manual: "Manual",
    automatic: "Automatic",
    "semi-automatic": "Semi-automatic",
    cvt: "CVT (Continuously Variable Transmission)",
    valid: "Validate",
  },
// Allemand
    de: {
      welcome: "Willkommen",
      login: "Anmelden",
      board: "Dashboard",
      logout: "Abmelden",
      optional: "Optional",
      service: "Service",
      Convoyage: {
        name: "Überführung",
        title: "Ihr Fahrzeug, unsere Route",
        description: "Transport von Punkt A → Punkt B in ganz Frankreich und Europa, durchgeführt von einem professionellen Fahrer für eine sichere und zuverlässige Abwicklung."
      },
      Remorquage: {
        name: "Abschleppen",
        title: "Ihr Fahrzeug, unsere Route",
        description: "Sicherer Transport Ihres Fahrzeugs zu einer Partnerwerkstatt oder an eine Adresse Ihrer Wahl."
      },
      Dépannage: {
        name: "Pannenhilfe",
        title: "Ihr Fahrzeug, unsere Route",
        description: [
          "Pannenhilfe vor Ort: Schneller Eingriff bei häufigen mechanischen Pannen.",
          "Kraftstoff-Pannenhilfe: Kraftstofflieferung vor Ort bei leerem Tank.",
          "Elektrische Pannenhilfe: Sofortige Hilfe mit Batterie-Booster oder tragbarer EV-Station für Elektrofahrzeuge."
        ]
      },
      subtitle: "Maßgeschneiderte Fahrzeugübernahme",
      why_choose_us: "Warum uns wählen?",
      reserve: "Reservieren",
      offersTitle: "Unsere Angebote",
      deliveryDescription: "Maßgeschneiderte Lieferung in ganz Europa",
      flexibility: "Maximale Flexibilität",
      flexibilityDescription: "Maßgeschneidert für jede Fahrt. Wir passen unsere Dienste an Ihre spezifischen Bedürfnisse an, sei es für den Fahrzeugtyp, das Timing oder besondere Anforderungen.",
      security: "Garantierte Sicherheit",
      securityDescription: "Erfahrene Fahrer und geeignete Fahrzeuge. Unsere Fachleute sind geschult, um alle Arten von Fahrzeugen zu handhaben, und unsere Flotte ist mit den neuesten Sicherheitstechnologien ausgestattet.",
      qualityPrice: "Unschlagbares Preis-Leistungs-Verhältnis",
      qualityPriceDescription: "Wettbewerbsfähige Preise für Premium-Service. Wir bieten vollständige Transparenz bei unseren Preisen, ohne versteckte Kosten, bei gleichzeitiger Aufrechterhaltung eines außergewöhnlichen Serviceniveaus.",
      peaceOfMind: "Absolute Sorglosigkeit",
      peaceOfMindDescription: "Aufgeschobene Zahlung, Sie zahlen erst, wenn Ihr Fahrzeug am Ziel angekommen ist. Diese Zahlungspolitik gibt Ihnen Seelenfrieden während des gesamten Lieferprozesses.",
      departLocation: "Abfahrtsort (Frankreich)",
      arrivalLocation: "Ankunftsorte",
      vehicleType: "Fahrzeugtyp",
      citadine: "Stadtauto",
      moto: "Motorrad",
      camion: "Lastwagen",
      comment: "Kommentar",
      contact: "Kontakt",
      needMorePreciseAddress: "Eine genauere Adresse mit Straße wird benötigt.",
      vehicleTypes: ['Motorrad', 'Stadtauto', 'Sport', 'Limousine', 'SUV', 'Van', 'Lastwagen (<3.5t)', 'Lastwagen (>3.5t)'],
      vehicle: "Fahrzeug",
      makeAndModel: "Marke und Modell",
      numberPlate: "Kennzeichen",
      seatingCapacity: "Sitzkapazität",
      gearbox: "Getriebe",
      piloteExpress: {
        title: "1. Der Express-Fahrer",
        description: "Ein professioneller Fahrer übernimmt das Steuer Ihres Fahrzeugs für eine direkte Zustellung. Ideal für schnelle und personalisierte Lieferung.",
        features: [
          "Tür-zu-Tür-Lieferung",
          "Erfahrene und zertifizierte Fahrer"
        ]
      },
      coconRoulant: {
        title: "2. Der Rollende Kokon",
        description: "Ihr Fahrzeug reist bequem in einem spezialisierten Lkw, wodurch Kilometerstand und Zustand erhalten bleiben. Perfekt für Luxus- oder Sammlerfahrzeuge.",
        features: [
          "Maximaler Schutz vor Witterungseinflüssen",
          "Mehrfahrzeugtransport möglich"
        ]
      },
      card1Title: "Maximale Flexibilität",
      card1Description: "Maßgeschneidert für jede Fahrt. Wir passen unsere Dienste an Ihre spezifischen Bedürfnisse an, sei es für den Fahrzeugtyp, das Timing oder besondere Anforderungen.",
      card2Title: "Garantierte Sicherheit",
      card2Description: "Erfahrene Fahrer und geeignete Fahrzeuge. Unsere Fachleute sind geschult, um alle Arten von Fahrzeugen zu handhaben, und unsere Flotte ist mit den neuesten Sicherheitstechnologien ausgestattet.",
      card3Title: "Unschlagbares Preis-Leistungs-Verhältnis",
      card3Description: "Wettbewerbsfähige Preise für Premium-Service. Wir bieten vollständige Transparenz bei unseren Preisen, ohne versteckte Kosten, bei gleichzeitiger Aufrechterhaltung eines außergewöhnlichen Serviceniveaus.",
      card4Title: "Absolute Sorglosigkeit",
      card4Description: "Aufgeschobene Zahlung, Sie zahlen erst, wenn Ihr Fahrzeug am Ziel angekommen ist. Diese Zahlungspolitik gibt Ihnen Seelenfrieden während des gesamten Lieferprozesses.",
      footer: "Vertrauen Sie AMSTRAM für den Transport Ihres Fahrzeugs und erleben Sie ein Liefererlebnis wie kein anderes!",
      terms: "Allgemeine Geschäftsbedingungen",
      privacy: "Datenschutzrichtlinie",
      phone: "Telefon",
      telephone: "Telefon",
      phoneNumber: "Telefonnummer beginnt mit + (+337 oder +336)",
      enterPhoneNumber: "Geben Sie Ihre Telefonnummer ein",
      vehiculeAvailability: "Fahrzeugverfügbarkeit",
      collectionNoEarlierThan: "Abholung nicht früher als",
      deliveryUntilHelp: "Das Abholdatum muss mindestens 3 Tage nach dem Sammeldatum liegen",
      deliveryUntil: "Lieferung bis spätestens",
      collectionNoEarlierThanHelp: "Das Abholdatum muss mindestens 24 Stunden ab heute sein",
      availabilityDescription: "Je länger der Nutzungszeitraum, desto schneller finden wir einen Fahrer für Sie",
      addContact: "Kontakt hinzufügen",
      cancel: "Abbrechen",
      addNewContact: "Neuen Kontakt hinzufügen",
      selectContact: "Kontakt auswählen",
      commentsDriver: "Kommentar für den Fahrer",
      myRoutes: "Meine Fahrten",
      verifyEmail: "E-Mail-Bestätigung",
      depannage_type: "Art der Panne",
      depannage: [
        { name: "Mechanisch", icon: "Wrench" },
        { name: "Kraftstoff", icon: "Fuel" },
        { name: "Elektrisch", icon: "PlugZap" },
        { name: "Entleerung", icon: "Droplets" }
      ],
      description1: "Ob Privatperson oder Unternehmen, AMSTRAM bietet eine auf Ihre Bedürfnisse zugeschnittene Fahrzeugtransportlösung.",
      ownerContact: "Eigentümerkontakt",
      departure: "Abfahrt",
      arrival: "Ankunft",
      availability: "Verfügbarkeit",
      vehicleDetails: "Fahrzeugdetails",
      price: "Preis",
      status: "Status",
      type: "Typ",
      make: "Marke",
      licensePlate: "Kennzeichen",
      capacity: "Kapazität",
      transmission: "Getriebe",
      payNow: "JETZT BEZAHLEN",
      paymentSuccess: "Zahlung erfolgreich durchgeführt",
      loading: "Routeninformationen werden geladen...",
      detail: "Details anzeigen",
      calculatingPrice: "Wird berechnet...",
      calculatingPriceMessage: "Wir berechnen den besten Preis für Ihre Fahrt.",
      phoneVerification: "Telefonverifizierung",
      titleVerified: "Nummer verifiziert",
      enterCode: "Geben Sie den per SMS erhaltenen Code ein",
      sendCode: "Code senden",
      verifyNumber: "Nummer verifizieren",
      verifyCode: "Code verifizieren",
      smsSentTo: "SMS gesendet an",
      resendCode: "Code erneut senden",
      phoneNumberFormat: "Die Telefonnummer muss mit + beginnen.",
      invalidPhoneNumber: "Ungültige Telefonnummer, bitte versuchen Sie es erneut",
      phoneUpdateError: "Fehler beim Aktualisieren der Telefonnummer, bitte versuchen Sie es erneut",
      incorrectCodeError: "Falscher Code, bitte versuchen Sie es erneut",
      verificationError: "Fehler bei der Telefonnummerverifizierung, bitte versuchen Sie es erneut",
      enterMakeAndModel: "Marke und Modell eingeben...",
      enterNumberPlate: "AA-123-AA",
      seats: "Sitze",
      enterAdditionalComments: "Zusätzliche Kommentare eingeben...",
      manual: "Manuell",
      automatic: "Automatik",
      "semi-automatic": "Semi-automatico",
      cvt: "CVT (Trasmissione a variazione continua)",
      valid: "Bestätigen",
    },
  
    // Portugais
    pt: {
      welcome: "Bem-vindo",
      login: "Entrar",
      board: "Painel de controle",
      logout: "Sair",
      optional: "Opcional",
      service: "Serviço",
      selectService: "Selecione seu serviço",
      chooseService: "Escolha um serviço",
      totalPrice: "Preço total",
      Convoyage: {
        name: "Transporte",
        title: "Seu veículo, nossa rota",
        description: "Transporte do ponto A → ponto B em toda a França e Europa, fornecido por um motorista profissional para um manuseio seguro e confiável."
      },
      Remorquage: {
        name: "Reboque",
        title: "Seu veículo, nossa rota",
        description: "Transporte seguro do seu veículo para uma oficina parceira ou endereço de sua escolha."
      },
      Dépannage: {
        name: "Assistência",
        title: "Seu veículo, nossa rota",
        description: [
          "Assistência no local: Intervenção rápida para falhas mecânicas comuns.",
          "Assistência de combustível: Entrega de combustível no local em caso de tanque vazio.",
          "Assistência elétrica: Ajuda imediata com reforço de bateria ou estação EV portátil para veículos elétricos."
        ]
      },
      subtitle: "Serviço de transporte de veículos sob medida",
      why_choose_us: "Por que nos escolher?",
      reserve: "Reservar",
      offersTitle: "Nossas ofertas",
      deliveryDescription: "Entrega personalizada em toda a Europa",
      flexibility: "Flexibilidade máxima",
      flexibilityDescription: "Personalizado para cada viagem. Adaptamos nossos serviços às suas necessidades específicas, seja para o tipo de veículo, tempo ou requisitos especiais.",
      security: "Segurança garantida",
      securityDescription: "Motoristas experientes e veículos adequados. Nossos profissionais são treinados para lidar com todos os tipos de veículos, e nossa frota está equipada com as mais recentes tecnologias de segurança.",
      qualityPrice: "Relação qualidade-preço imbatível",
      qualityPriceDescription: "Tarifas competitivas para um serviço premium. Oferecemos total transparência em nossos preços, sem taxas ocultas, mantendo um nível excepcional de serviço.",
      peaceOfMind: "Tranquilidade total",
      peaceOfMindDescription: "Pagamento diferido, você só paga quando seu veículo chegar ao destino. Esta política de pagamento garante sua tranquilidade durante todo o processo de entrega.",
      departLocation: "Local de partida (França)",
      arrivalLocation: "Locais de chegada",
      vehicleType: "Tipo de veículo",
      citadine: "Carro urbano",
      moto: "Motocicleta",
      camion: "Caminhão",
      comment: "Comentário",
      contact: "Contato",
      needMorePreciseAddress: "Precisa de um endereço mais preciso, com uma rua.",
      vehicleTypes: ['Motocicleta', 'Carro urbano', 'Esportivo', 'Sedan', 'SUV', 'Van', 'Caminhão (<3.5t)', 'Caminhão (>3.5t)'],
      vehicle: "Veículo",
      makeAndModel: "Marca e modelo",
      numberPlate: "Placa",
      seatingCapacity: "Capacidade de assentos",
      gearbox: "Câmbio",
      piloteExpress: {
        title: "1. O Motorista Expresso",
        description: "Um motorista profissional assume o volante do seu veículo para uma entrega direta. Ideal para entrega rápida e personalizada.",
        features: [
          "Entrega porta a porta",
          "Motoristas experientes e certificados"
        ]
      },
      coconRoulant: {
        title: "2. O Casulo Rolante",
        description: "Seu veículo viaja confortavelmente em um caminhão especializado, preservando sua quilometragem e condição. Perfeito para veículos de luxo ou de coleção.",
        features: [
          "Proteção máxima contra os elementos",
          "Transporte multi-veículos possível"
        ]
      },
      card1Title: "Flexibilidade máxima",
      card1Description: "Personalizado para cada viagem. Adaptamos nossos serviços às suas necessidades específicas, seja para o tipo de veículo, tempo ou requisitos especiais.",
      card2Title: "Segurança garantida",
      card2Description: "Motoristas experientes e veículos adequados. Nossos profissionais são treinados para lidar com todos os tipos de veículos, e nossa frota está equipada com as mais recentes tecnologias de segurança.",
      card3Title: "Relação qualidade-preço imbatível",
      card3Description: "Tarifas competitivas para um serviço premium. Oferecemos total transparência em nossos preços, sem taxas ocultas, mantendo um nível excepcional de serviço.",
      card4Title: "Tranquilidade total",
      card4Description: "Pagamento diferido, você só paga quando seu veículo chegar ao destino. Esta política de pagamento garante sua tranquilidade durante todo o processo de entrega.",
      footer: "Confie na AMSTRAM para o transporte do seu veículo e desfrute de uma experiência de entrega como nenhuma outra!",
      terms: "Termos e Condições",
      privacy: "Política de Privacidade",
      phone: "Telefone",
      telephone: "Telefone",
      phoneNumber: "Número de telefone começa com + (+337 ou +336)",
      enterPhoneNumber: "Digite seu número de telefone",
      vehiculeAvailability: "Disponibilidade do veículo",
      collectionNoEarlierThan: "Coleta não antes de",
      deliveryUntilHelp: "A data de coleta deve ser pelo menos 3 dias após a data de coleta",
      deliveryUntil: "Entrega até",
      collectionNoEarlierThanHelp: "A data de coleta deve ser pelo menos 24 horas a partir de hoje",
      availabilityDescription: "Quanto maior o período de disponibilidade, mais rápido encontraremos um motorista para você",
      addContact: "Adicionar contato",
      cancel: "Cancelar",
      addNewContact: "Adicionar novo contato",
      selectContact: "Selecionar contato",
      commentsDriver: "Comentário para o motorista",
      myRoutes: "Minhas rotas",
      verifyEmail: "Verificação de e-mail",
      depannage_type: "Tipo de assistência",
      depannage: [
        { name: "Mecânica", icon: "Wrench" },
        { name: "Combustível", icon: "Fuel" },
        { name: "Elétrica", icon: "PlugZap" },
        { name: "Esvaziamento", icon: "Droplets" }
      ],
      description1: "Seja você um indivíduo privado ou uma empresa, a AMSTRAM oferece uma solução de transporte de veículos adaptada às suas necessidades.",
      ownerContact: "Contato do proprietário",
      departure: "Partida",
      arrival: "Chegada",
      availability: "Disponibilidade",
      vehicleDetails: "Detalhes do veículo",
      price: "Preço",
      status: "Status",
      type: "Tipo",
      make: "Marca",
      licensePlate: "Placa",
      capacity: "Capacidade",
      transmission: "Transmissão",
      payNow: "PAGAR AGORA",
      paymentSuccess: "Pagamento realizado com sucesso",
      loading: "Carregando informações da rota...",
      detail: "Ver detalhes",
      calculatingPrice: "Calculando...",
      calculatingPriceMessage: "Estamos calculando o melhor preço para sua viagem.",
      phoneVerification: "Verificação do telefone",
      titleVerified: "Número verificado",
      enterCode: "Digite o código que você recebeu por SMS",
      sendCode: "Enviar código",
      verifyNumber: "Verificar número",
      verifyCode: "Verificar código",
      smsSentTo: "SMS enviado para",
      resendCode: "Reenviar código",
      phoneNumberFormat: "O número de telefone deve começar com +.",
      invalidPhoneNumber: "Número de telefone inválido, por favor tente novamente",
      phoneUpdateError: "Erro ao atualizar número de telefone, por favor tente novamente",
      incorrectCodeError: "Código incorreto, por favor tente novamente",
      verificationError: "Erro ao verificar número de telefone, por favor tente novamente",
      enterMakeAndModel: "Digite a marca e o modelo...",
      enterNumberPlate: "AA-123-AA",
      seats: "lugares",
      enterAdditionalComments: "Digite comentários adicionais...",
      manual: "Manual",
      automatic: "Automático",
      "semi-automatic": "Semi-automático",
      cvt: "CVT (Transmissão Continuamente Variável)",
      valid: "Validar",
    },
  
    // Italien
    it: {
      welcome: "Benvenuto",
      login: "Accedi",
      board: "Pannello di controllo",
      logout: "Disconnetti",
      optional: "Opzionale",
      service: "Servizio",
      selectService: "Seleziona il tuo servizio",
      chooseService: "Scegli un servizio",
      totalPrice: "Prezzo totale",
      Convoyage: {
        name: "Trasporto",
        title: "Il tuo veicolo, la nostra strada",
        description: "Trasporto dal punto A → punto B in tutta la Francia e l'Europa, fornito da un conducente professionale per una gestione sicura e affidabile."
      },
      Remorquage: {
        name: "Rimorchio",
        title: "Il tuo veicolo, la nostra strada",
        description: "Trasporto sicuro del tuo veicolo a un'officina partner o all'indirizzo di tua scelta."
      },
      Dépannage: {
        name: "Assistenza",
        title: "Il tuo veicolo, la nostra strada",
        description: [
          "Assistenza sul posto: Intervento rapido per guasti meccanici comuni.",
          "Assistenza carburante: Consegna di carburante sul posto in caso di serbatoio vuoto.",
          "Assistenza elettrica: Aiuto immediato con booster per batteria o stazione EV portatile per veicoli elettrici."
        ]
      },
      subtitle: "Servizio di trasporto veicoli su misura",
      why_choose_us: "Perché sceglierci?",
      reserve: "Prenota",
      offersTitle: "Le nostre offerte",
      deliveryDescription: "Consegna personalizzata in tutta Europa",
      flexibility: "Massima flessibilità",
      flexibilityDescription: "Su misura per ogni viaggio. Adattiamo i nostri servizi alle tue esigenze specifiche, che si tratti del tipo di veicolo, dei tempi o di requisiti speciali.",
      security: "Sicurezza garantita",
      securityDescription: "Conducenti esperti e veicoli adatti. I nostri professionisti sono formati per gestire tutti i tipi di veicoli e la nostra flotta è dotata delle più recenti tecnologie di sicurezza.",
      qualityPrice: "Rapporto qualità-prezzo imbattibile",
      qualityPriceDescription: "Tariffe competitive per un servizio premium. Offriamo totale trasparenza sui nostri prezzi, senza costi nascosti, mantenendo un livello di servizio eccezionale.",
      peaceOfMind: "Totale tranquillità",
      peaceOfMindDescription: "Pagamento differito, paghi solo quando il tuo veicolo è arrivato a destinazione. Questa politica di pagamento ti garantisce tranquillità durante tutto il processo di consegna.",
      departLocation: "Luogo di partenza (Francia)",
      arrivalLocation: "Luoghi di arrivo",
      vehicleType: "Tipo di veicolo",
      citadine: "Citycar",
      moto: "Moto",
      camion: "Camion",
      comment: "Commento",
      contact: "Contatto",
      needMorePreciseAddress: "Serve un indirizzo più preciso, con una strada.",
      vehicleTypes: ['Moto', 'Citycar', 'Sportiva', 'Berlina', 'SUV', 'Furgone', 'Camion (<3.5t)', 'Camion (>3.5t)'],
      vehicle: "Veicolo",
      makeAndModel: "Marca e modello",
      numberPlate: "Targa",
      seatingCapacity: "Capacità di posti",
      gearbox: "Cambio",
      piloteExpress: {
        title: "1. Il Conducente Express",
        description: "Un conducente professionista prende il volante del tuo veicolo per una consegna diretta. Ideale per una consegna rapida e personalizzata.",
        features: [
          "Consegna porta a porta",
          "Conducenti esperti e certificati"
        ]
      },
      coconRoulant: {
        title: "2. Il Bozzolo Rotante",
        description: "Il tuo veicolo viaggia comodamente in un camion specializzato, preservando il chilometraggio e le condizioni. Perfetto per veicoli di lusso o da collezione.",
        features: [
          "Massima protezione contro gli elementi",
          "Possibile trasporto multi-veicolo"
        ]
      },
      card1Title: "Massima flessibilità",
      card1Description: "Su misura per ogni viaggio. Adattiamo i nostri servizi alle tue esigenze specifiche, che si tratti del tipo di veicolo, dei tempi o di requisiti speciali.",
      card2Title: "Sicurezza garantita",
      card2Description: "Conducenti esperti e veicoli adatti. I nostri professionisti sono formati per gestire tutti i tipi di veicoli e la nostra flotta è dotata delle più recenti tecnologie di sicurezza.",
      card3Title: "Rapporto qualità-prezzo imbattibile",
      card3Description: "Tariffe competitive per un servizio premium. Offriamo totale trasparenza sui nostri prezzi, senza costi nascosti, mantenendo un livello di servizio eccezionale.",
      card4Title: "Totale tranquillità",
      card4Description: "Pagamento differito, paghi solo quando il tuo veicolo è arrivato a destinazione. Questa politica di pagamento ti garantisce tranquillità durante tutto il processo di consegna.",
      footer: "Affidati ad AMSTRAM per il trasporto del tuo veicolo e goditi un'esperienza di consegna senza eguali!",
      terms: "Termini e Condizioni",
      privacy: "Politica sulla Privacy",
      phone: "Telefono",
      telephone: "Telefono",
      phoneNumber: "Il numero di telefono inizia con + (+337 o +336)",
      enterPhoneNumber: "Inserisci il tuo numero di telefono",
      vehiculeAvailability: "Disponibilità del veicolo",
      collectionNoEarlierThan: "Ritiro non prima di",
      deliveryUntilHelp: "La data di ritiro deve essere almeno 3 giorni dopo la data di raccolta",
      deliveryUntil: "Consegna entro",
      collectionNoEarlierThanHelp: "La data di ritiro deve essere almeno 24 ore da oggi",
      availabilityDescription: "Più lungo è il periodo di disponibilità, più velocemente troveremo un conducente per te",
      addContact: "Aggiungi contatto",
      cancel: "Annulla",
      addNewContact: "Aggiungi nuovo contatto",
      selectContact: "Seleziona contatto",
      commentsDriver: "Commento per il conducente",
      myRoutes: "I miei percorsi",
      verifyEmail: "Verifica email",
      depannage_type: "Tipo di assistenza",
      depannage: [
        { name: "Meccanica", icon: "Wrench" },
        { name: "Carburante", icon: "Fuel" },
        { name: "Elettrica", icon: "PlugZap" },
        { name: "Svuotamento", icon: "Droplets" }
      ],
      description1: "Che tu sia un privato o un'azienda, AMSTRAM offre una soluzione di trasporto veicoli su misura per le tue esigenze.",
      ownerContact: "Contatto proprietario",
      departure: "Partenza",
      arrival: "Arrivo",
      availability: "Disponibilità",
      vehicleDetails: "Dettagli del veicolo",
      price: "Prezzo",
      status: "Stato",
      type: "Tipo",
      make: "Marca",
      licensePlate: "Targa",
      capacity: "Capacità",
      transmission: "Trasmissione",
      payNow: "PAGA ORA",
      paymentSuccess: "Pagamento effettuato con successo",
      loading: "Caricamento delle informazioni sul percorso...",
      detail: "Vedi dettagli",
      calculatingPrice: "Calcolo in corso...",
      calculatingPriceMessage: "Stiamo calcolando il miglior prezzo per il tuo viaggio.",
      phoneVerification: "Verifica del telefono",
      titleVerified: "Numero verificato",
      enterCode: "Inserisci il codice ricevuto via SMS",
      sendCode: "Invia codice",
      verifyNumber: "Verifica numero",
      verifyCode: "Verifica codice",
      smsSentTo: "SMS inviato a",
      resendCode: "Rinvia codice",
      phoneNumberFormat: "Il numero di telefono deve iniziare con +.",
      invalidPhoneNumber: "Numero di telefono non valido, riprova",
      phoneUpdateError: "Errore nell'aggiornamento del numero, riprova",
      incorrectCodeError: "Codice non corretto, riprova",
      verificationError: "Errore nella verifica del numero, riprova",
      enterMakeAndModel: "Inserisci marca e modello...",
      enterNumberPlate: "AA-123-AA",
      seats: "posti",
      enterAdditionalComments: "Inserisci commenti aggiuntivi...",
      manual: "Manuale",
      automatic: "Automatico",
      "semi-automatic": "Semi-automatico",
      cvt: "CVT (Trasmissione a variazione continua)",
      valid: "Convalida",
    },
  
    // Espagnol
    es: {
      welcome: "Bienvenido",
      login: "Iniciar sesión",
      board: "Panel de control",
      logout: "Cerrar sesión",
      optional: "Opcional",
      service: "Servicio",
      selectService: "Seleccione su servicio",
      chooseService: "Elija un servicio",
      totalPrice: "Precio total",
      Convoyage: {
        name: "Transporte",
        title: "Su vehículo, nuestra ruta",
        description: "Transporte del punto A → punto B en toda Francia y Europa, proporcionado por un conductor profesional para una gestión segura y fiable."
      },
      Remorquage: {
        name: "Remolque",
        title: "Su vehículo, nuestra ruta",
        description: "Transporte seguro de su vehículo a un taller asociado o a la dirección de su elección."
      },
      Dépannage: {
        name: "Asistencia",
        title: "Su vehículo, nuestra ruta",
        description: [
          "Asistencia en el lugar: Intervención rápida para averías mecánicas comunes.",
          "Asistencia de combustible: Entrega de combustible en el lugar en caso de quedarse sin gasolina.",
          "Asistencia eléctrica: Ayuda inmediata con un reforzador de batería o una estación VE portátil para vehículos eléctricos."
        ]
      },
      subtitle: "Servicio de transporte de vehículos a medida",
      why_choose_us: "¿Por qué elegirnos?",
      reserve: "Reservar",
      offersTitle: "Nuestras ofertas",
      deliveryDescription: "Entrega personalizada en toda Europa",
      flexibility: "Máxima flexibilidad",
      flexibilityDescription: "A medida para cada viaje. Adaptamos nuestros servicios a sus necesidades específicas, ya sea para el tipo de vehículo, el tiempo o los requisitos especiales.",
      security: "Seguridad garantizada",
      securityDescription: "Conductores experimentados y vehículos adecuados. Nuestros profesionales están formados para manejar todo tipo de vehículos, y nuestra flota está equipada con las últimas tecnologías de seguridad.",
      qualityPrice: "Relación calidad-precio imbatible",
      qualityPriceDescription: "Tarifas competitivas para un servicio premium. Ofrecemos total transparencia en nuestros precios, sin costes ocultos, manteniendo un nivel de servicio excepcional.",
      peaceOfMind: "Total tranquilidad",
      peaceOfMindDescription: "Pago diferido, solo paga cuando su vehículo ha llegado a su destino. Esta política de pago le asegura tranquilidad durante todo el proceso de entrega.",
      departLocation: "Lugar de salida (Francia)",
      arrivalLocation: "Lugares de llegada",
      vehicleType: "Tipo de vehículo",
      citadine: "Coche urbano",
      moto: "Moto",
      camion: "Camión",
      comment: "Comentario",
      contact: "Contacto",
      needMorePreciseAddress: "Necesita una dirección más precisa, con una calle.",
      vehicleTypes: ['Moto', 'Coche urbano', 'Deportivo', 'Berlina', 'SUV', 'Furgoneta', 'Camión (<3.5t)', 'Camión (>3.5t)'],
      vehicle: "Vehículo",
      makeAndModel: "Marca y modelo",
      numberPlate: "Matrícula",
      seatingCapacity: "Capacidad de asientos",
      gearbox: "Caja de cambios",
      piloteExpress: {
        title: "1. El Conductor Express",
        description: "Un conductor profesional toma el volante de su vehículo para una entrega directa. Ideal para una entrega rápida y personalizada.",
        features: [
          "Entrega puerta a puerta",
          "Conductores experimentados y certificados"
        ]
      },
      coconRoulant: {
        title: "2. El Capullo Rodante",
        description: "Su vehículo viaja cómodamente en un camión especializado, preservando su kilometraje y estado. Perfecto para vehículos de lujo o de colección.",
        features: [
          "Máxima protección contra los elementos",
          "Posible transporte multi-vehículo"
        ]
      },
      card1Title: "Máxima flexibilidad",
      card1Description: "A medida para cada viaje. Adaptamos nuestros servicios a sus necesidades específicas, ya sea para el tipo de vehículo, el tiempo o los requisitos especiales.",
      card2Title: "Seguridad garantizada",
      card2Description: "Conductores experimentados y vehículos adecuados. Nuestros profesionales están formados para manejar todo tipo de vehículos, y nuestra flota está equipada con las últimas tecnologías de seguridad.",
      card3Title: "Relación calidad-precio imbatible",
      card3Description: "Tarifas competitivas para un servicio premium. Ofrecemos total transparencia en nuestros precios, sin costes ocultos, manteniendo un nivel de servicio excepcional.",
      card4Title: "Total tranquilidad",
      card4Description: "Pago diferido, solo paga cuando su vehículo ha llegado a su destino. Esta política de pago le asegura tranquilidad durante todo el proceso de entrega.",
      footer: "¡Confíe en AMSTRAM para el transporte de su vehículo y disfrute de una experiencia de entrega como ninguna otra!",
      terms: "Términos y Condiciones",
      privacy: "Política de Privacidad",
      phone: "Teléfono",
      telephone: "Teléfono",
      phoneNumber: "El número de teléfono comienza con + (+337 o +336)",
      enterPhoneNumber: "Introduzca su número de teléfono",
      vehiculeAvailability: "Disponibilidad del vehículo",
      collectionNoEarlierThan: "Recogida no antes de",
      deliveryUntilHelp: "La fecha de recogida debe ser al menos 3 días después de la fecha de recogida",
      deliveryUntil: "Entrega hasta",
      collectionNoEarlierThanHelp: "La fecha de recogida debe ser al menos 24 horas a partir de hoy",
      availabilityDescription: "Cuanto mayor sea el período de disponibilidad, más rápido encontraremos un conductor para usted",
      addContact: "Añadir contacto",
      cancel: "Cancelar",
      addNewContact: "Añadir nuevo contacto",
      selectContact: "Seleccionar contacto",
      commentsDriver: "Comentario para el conductor",
      myRoutes: "Mis rutas",
      verifyEmail: "Verificación de correo electrónico",
      depannage_type: "Tipo de asistencia",
      depannage: [
        { name: "Mecánica", icon: "Wrench" },
        { name: "Combustible", icon: "Fuel" },
        { name: "Eléctrica", icon: "PlugZap" },
        { name: "Vaciado", icon: "Droplets" }
      ],
      description1: "Ya sea un particular o una empresa, AMSTRAM ofrece una solución de transporte de vehículos adaptada a sus necesidades.",
      ownerContact: "Contacto del propietario",
      departure: "Salida",
      arrival: "Llegada",
      availability: "Disponibilidad",
      vehicleDetails: "Detalles del vehículo",
      price: "Precio",
      status: "Estado",
      type: "Tipo",
      make: "Marca",
      licensePlate: "Matrícula",
      capacity: "Capacidad",
      transmission: "Transmisión",
      payNow: "PAGAR AHORA",
      paymentSuccess: "Pago realizado con éxito",
      loading: "Cargando información de la ruta...",
      detail: "Ver detalles",
      calculatingPrice: "Calculando...",
      calculatingPriceMessage: "Estamos calculando el mejor precio para su viaje.",
      phoneVerification: "Verificación del teléfono",
      titleVerified: "Número verificado",
      enterCode: "Introduzca el código que recibió por SMS",
      sendCode: "Enviar código",
      verifyNumber: "Verificar número",
      verifyCode: "Verificar código",
      smsSentTo: "SMS enviado a",
      resendCode: "Reenviar código",
      phoneNumberFormat: "El número de teléfono debe comenzar con +.",
      invalidPhoneNumber: "Número de teléfono inválido, por favor inténtelo de nuevo",
      phoneUpdateError: "Error al actualizar el número, por favor inténtelo de nuevo",
      incorrectCodeError: "Código incorrecto, por favor inténtelo de nuevo",
      verificationError: "Error al verificar el número, por favor inténtelo de nuevo",
      enterMakeAndModel: "Introduzca marca y modelo...",
      enterNumberPlate: "AA-123-AA",
      seats: "plazas",
      enterAdditionalComments: "Introduzca comentarios adicionales...",
      manual: "Manual",
      automatic: "Automático",
      "semi-automatic": "Semi-automático",
      cvt: "CVT (Transmisión Continuamente Variable)",
      valid: "Validar",
    },
  
    // Néerlandais
    nl: {
      welcome: "Welkom",
      login: "Inloggen",
      board: "Dashboard",
      logout: "Uitloggen",
      optional: "Optioneel",
      service: "Service",
      selectService: "Selecteer uw service",
      chooseService: "Kies een service",
      totalPrice: "Totaal prijs",
      Convoyage: {
        name: "Transport",
        title: "Uw voertuig, onze route",
        description: "Transport van punt A → punt B door heel Frankrijk en Europa, verzorgd door een professionele chauffeur voor een veilige en betrouwbare afhandeling."
      },
      Remorquage: {
        name: "Sleepdienst",
        title: "Uw voertuig, onze route",
        description: "Veilig transport van uw voertuig naar een partnergarage of een adres naar keuze."
      },
      Dépannage: {
        name: "Pechverhelping",
        title: "Uw voertuig, onze route",
        description: [
          "Pechverhelping ter plaatse: Snelle interventie voor veelvoorkomende mechanische storingen.",
          "Brandstof pechverhelping: Brandstoflevering ter plaatse in geval van een lege tank.",
          "Elektrische pechverhelping: Onmiddellijke hulp met een batterijbooster of draagbaar EV-station voor elektrische voertuigen."
        ]
      },
      subtitle: "Voertuigtransport op maat",
      why_choose_us: "Waarom ons kiezen?",
      reserve: "Reserveren",
      offersTitle: "Onze aanbiedingen",
      deliveryDescription: "Levering op maat in heel Europa",
      flexibility: "Maximale flexibiliteit",
      flexibilityDescription: "Op maat voor elke reis. We passen onze diensten aan uw specifieke behoeften aan, of het nu gaat om het type voertuig, de timing of speciale vereisten.",
      security: "Gegarandeerde veiligheid",
      securityDescription: "Ervaren chauffeurs en geschikte voertuigen. Onze professionals zijn opgeleid om alle soorten voertuigen te hanteren, en onze vloot is uitgerust met de nieuwste veiligheidstechnologieën.",
      qualityPrice: "Onverslaanbare prijs-kwaliteitverhouding",
      qualityPriceDescription: "Concurrerende tarieven voor een premium service. We bieden volledige transparantie over onze prijzen, zonder verborgen kosten, terwijl we een uitzonderlijk serviceniveau handhaven.",
      peaceOfMind: "Totale gemoedsrust",
      peaceOfMindDescription: "Uitgestelde betaling, u betaalt pas wanneer uw voertuig op de bestemming is aangekomen. Dit betalingsbeleid zorgt voor gemoedsrust tijdens het hele leveringsproces.",
      departLocation: "Vertrekplaats (Frankrijk)",
      arrivalLocation: "Aankomstplaatsen",
      vehicleType: "Voertuigtype",
      citadine: "Stadsauto",
      moto: "Motor",
      camion: "Vrachtwagen",
      comment: "Opmerking",
      contact: "Contact",
      needMorePreciseAddress: "Een preciezer adres nodig, met een straat.",
      vehicleTypes: ['Motor', 'Stadsauto', 'Sport', 'Sedan', 'SUV', 'Bestelwagen', 'Vrachtwagen (<3.5t)', 'Vrachtwagen (>3.5t)'],
      vehicle: "Voertuig",
      makeAndModel: "Merk en model",
      numberPlate: "Kenteken",
      seatingCapacity: "Zitplaatscapaciteit",
      gearbox: "Versnellingsbak",
      piloteExpress: {
        title: "1. De Express Chauffeur",
        description: "Een professionele chauffeur neemt het stuur van uw voertuig over voor een directe levering. Ideaal voor snelle en gepersonaliseerde levering.",
        features: [
          "Deur-tot-deur levering",
          "Ervaren en gecertificeerde chauffeurs"
        ]
      },
      coconRoulant: {
        title: "2. De Rollende Cocon",
        description: "Uw voertuig reist comfortabel in een gespecialiseerde vrachtwagen, waardoor de kilometerstand en conditie behouden blijven. Perfect voor luxe of verzamelvoertuigen.",
        features: [
          "Maximale bescherming tegen de elementen",
          "Multivoertuig transport mogelijk"
        ]
      },
      card1Title: "Maximale flexibiliteit",
      card1Description: "Op maat voor elke reis. We passen onze diensten aan uw specifieke behoeften aan, of het nu gaat om het type voertuig, de timing of speciale vereisten.",
      card2Title: "Gegarandeerde veiligheid",
      card2Description: "Ervaren chauffeurs en geschikte voertuigen. Onze professionals zijn opgeleid om alle soorten voertuigen te hanteren, en onze vloot is uitgerust met de nieuwste veiligheidstechnologieën.",
      card3Title: "Onverslaanbare prijs-kwaliteitverhouding",
      card3Description: "Concurrerende tarieven voor een premium service. We bieden volledige transparantie over onze prijzen, zonder verborgen kosten, terwijl we een uitzonderlijk serviceniveau handhaven.",
      card4Title: "Totale gemoedsrust",
      card4Description: "Uitgestelde betaling, u betaalt pas wanneer uw voertuig op de bestemming is aangekomen. Dit betalingsbeleid zorgt voor gemoedsrust tijdens het hele leveringsproces.",
      footer: "Vertrouw op AMSTRAM voor het transport van uw voertuig en geniet van een leveringservaring als geen ander!",
      terms: "Algemene Voorwaarden",
      privacy: "Privacybeleid",
      phone: "Telefoon",
      telephone: "Telefoon",
      phoneNumber: "Telefoonnummer begint met + (+337 of +336)",
      enterPhoneNumber: "Voer uw telefoonnummer in",
      vehiculeAvailability: "Beschikbaarheid voertuig",
      collectionNoEarlierThan: "Ophaling niet eerder dan",
      deliveryUntilHelp: "De ophaaldatum moet minimaal 3 dagen na de ophaaldatum zijn",
      deliveryUntil: "Levering tot",
      collectionNoEarlierThanHelp: "De ophaaldatum moet minimaal 24 uur vanaf vandaag zijn",
      availabilityDescription: "Hoe langer de beschikbaarheidsperiode, hoe sneller we een chauffeur voor u vinden",
      addContact: "Contact toevoegen",
      cancel: "Annuleren",
      addNewContact: "Nieuw contact toevoegen",
      selectContact: "Contact selecteren",
      commentsDriver: "Opmerking voor de chauffeur",
      myRoutes: "Mijn routes",
      verifyEmail: "E-mailverificatie",
      depannage_type: "Type pechverhelping",
      depannage: [
        { name: "Mechanisch", icon: "Wrench" },
        { name: "Brandstof", icon: "Fuel" },
        { name: "Elektrisch", icon: "PlugZap" },
        { name: "Leging", icon: "Droplets" }
      ],
      description1: "Of u nu een particulier of een bedrijf bent, AMSTRAM biedt een voertuigtransportoplossing op maat van uw behoeften.",
      ownerContact: "Contact eigenaar",
      departure: "Vertrek",
      arrival: "Aankomst",
      availability: "Beschikbaarheid",
      vehicleDetails: "Voertuigdetails",
      price: "Prijs",
      status: "Status",
      type: "Type",
      make: "Merk",
      licensePlate: "Kenteken",
      capacity: "Capaciteit",
      transmission: "Transmissie",
      payNow: "NU BETALEN",
      paymentSuccess: "Betaling succesvol voltooid",
      loading: "Route-informatie laden...",
      detail: "Details bekijken",
      calculatingPrice: "Bezig met berekenen...",
      calculatingPriceMessage: "We berekenen de beste prijs voor uw reis.",
      phoneVerification: "Telefoonverificatie",
      titleVerified: "Nummer geverifieerd",
      enterCode: "Voer de code in die u per SMS heeft ontvangen",
      sendCode: "Code versturen",
      verifyNumber: "Nummer verifiëren",
      verifyCode: "Code verifiëren",
      smsSentTo: "SMS verzonden naar",
      resendCode: "Code opnieuw versturen",
      phoneNumberFormat: "Het telefoonnummer moet beginnen met +.",
      invalidPhoneNumber: "Ongeldig telefoonnummer, probeer het opnieuw",
      phoneUpdateError: "Fout bij het bijwerken van het telefoonnummer, probeer het opnieuw",
      incorrectCodeError: "Ongeldige code, probeer het opnieuw",
      verificationError: "Fout bij het verifiëren van het telefoonnummer, probeer het opnieuw",
      enterMakeAndModel: "Voer merk en model in...",
      enterNumberPlate: "AA-123-AA",
      seats: "plaatsen",
      enterAdditionalComments: "Voer extra opmerkingen in...",
      manual: "Handmatig",
      automatic: "Automatisch",
      "semi-automatic": "Halfautomatisch",
      cvt: "CVT (Continu Variabele Transmissie)",
      valid: "Valideren",
    },
  
    // Flamand/Néerlandais de Belgique (très proche du néerlandais mais avec quelques différences)
    vl: {
      welcome: "Welkom",
      login: "Aanmelden",
      board: "Dashboard",
      logout: "Afmelden",
      optional: "Optioneel",
      service: "Dienst",
      selectService: "Selecteer uw dienst",
      chooseService: "Kies een dienst",
      totalPrice: "Totaal prijs",
      Convoyage: {
        name: "Transport",
        title: "Uw voertuig, onze route",
        description: "Transport van punt A → punt B doorheen Frankrijk en Europa, verzorgd door een professionele chauffeur voor een veilige en betrouwbare afhandeling."
      },
      Remorquage: {
        name: "Takeldienst",
        title: "Uw voertuig, onze route",
        description: "Veilig transport van uw voertuig naar een partnergarage of een adres naar keuze."
      },
      Dépannage: {
        name: "Pechbijstand",
        title: "Uw voertuig, onze route",
        description: [
          "Pechbijstand ter plaatse: Snelle interventie voor veelvoorkomende mechanische defecten.",
          "Brandstof pechbijstand: Brandstoflevering ter plaatse in geval van een lege tank.",
          "Elektrische pechbijstand: Onmiddellijke hulp met een batterijbooster of draagbaar EV-station voor elektrische voertuigen."
        ]
      },
      subtitle: "Voertuigtransport op maat",
      why_choose_us: "Waarom voor ons kiezen?",
      reserve: "Reserveren",
      offersTitle: "Onze aanbiedingen",
      deliveryDescription: "Levering op maat doorheen Europa",
      flexibility: "Maximale flexibiliteit",
      flexibilityDescription: "Op maat voor elke rit. We passen onze diensten aan uw specifieke noden aan, of het nu gaat om het type voertuig, de timing of speciale vereisten.",
      security: "Gegarandeerde veiligheid",
      securityDescription: "Ervaren chauffeurs en geschikte voertuigen. Onze professionals zijn opgeleid om alle types voertuigen te hanteren, en onze vloot is uitgerust met de nieuwste veiligheidstechnologieën.",
      qualityPrice: "Onklopbare prijs-kwaliteitverhouding",
      qualityPriceDescription: "Competitieve tarieven voor een premium dienst. We bieden volledige transparantie over onze prijzen, zonder verborgen kosten, terwijl we een uitzonderlijk dienstniveau handhaven.",
      peaceOfMind: "Totale gemoedsrust",
      peaceOfMindDescription: "Uitgestelde betaling, u betaalt pas wanneer uw voertuig op de bestemming is aangekomen. Dit betalingsbeleid zorgt voor gemoedsrust tijdens het hele leveringsproces.",
      departLocation: "Vertrekplaats (Frankrijk)",
      arrivalLocation: "Aankomstplaatsen",
      vehicleType: "Voertuigtype",
      citadine: "Stadsauto",
      moto: "Motor",
      camion: "Vrachtwagen",
      comment: "Opmerking",
      contact: "Contact",
      needMorePreciseAddress: "Een nauwkeuriger adres nodig, met een straat.",
      vehicleTypes: ['Motor', 'Stadsauto', 'Sport', 'Berline', 'SUV', 'Bestelwagen', 'Vrachtwagen (<3.5t)', 'Vrachtwagen (>3.5t)'],
      vehicle: "Voertuig",
      makeAndModel: "Merk en model",
      numberPlate: "Nummerplaat",
      seatingCapacity: "Zitplaatscapaciteit",
      gearbox: "Versnellingsbak",
      piloteExpress: {
        title: "1. De Express Chauffeur",
        description: "Een professionele chauffeur neemt het stuur van uw voertuig over voor een directe levering. Ideaal voor snelle en gepersonaliseerde levering.",
        features: [
          "Deur-tot-deur levering",
          "Ervaren en gecertificeerde chauffeurs"
        ]
      },
      coconRoulant: {
        title: "2. De Rollende Cocon",
        description: "Uw voertuig reist comfortabel in een gespecialiseerde vrachtwagen, waardoor de kilometerstand en conditie behouden blijven. Perfect voor luxe of verzamelvoertuigen.",
        features: [
          "Maximale bescherming tegen de elementen",
          "Multivoertuig transport mogelijk"
        ]
      },
      card1Title: "Maximale flexibiliteit",
      card1Description: "Op maat voor elke rit. We passen onze diensten aan uw specifieke noden aan, of het nu gaat om het type voertuig, de timing of speciale vereisten.",
      card2Title: "Gegarandeerde veiligheid",
      card2Description: "Ervaren chauffeurs en geschikte voertuigen. Onze professionals zijn opgeleid om alle types voertuigen te hanteren, en onze vloot is uitgerust met de nieuwste veiligheidstechnologieën.",
      card3Title: "Onklopbare prijs-kwaliteitverhouding",
      card3Description: "Competitieve tarieven voor een premium dienst. We bieden volledige transparantie over onze prijzen, zonder verborgen kosten, terwijl we een uitzonderlijk dienstniveau handhaven.",
      card4Title: "Totale gemoedsrust",
      card4Description: "Uitgestelde betaling, u betaalt pas wanneer uw voertuig op de bestemming is aangekomen. Dit betalingsbeleid zorgt voor gemoedsrust tijdens het hele leveringsproces.",
      footer: "Vertrouw op AMSTRAM voor het transport van uw voertuig en geniet van een leveringservaring als geen ander!",
      terms: "Algemene Voorwaarden",
      privacy: "Privacybeleid",
      phone: "Telefoon",
      telephone: "Telefoon",
      phoneNumber: "Telefoonnummer begint met + (+337 of +336)",
      enterPhoneNumber: "Voer uw telefoonnummer in",
      vehiculeAvailability: "Beschikbaarheid voertuig",
      collectionNoEarlierThan: "Ophaling niet vroeger dan",
      deliveryUntilHelp: "De ophaaldatum moet minstens 3 dagen na de ophaaldatum zijn",
      deliveryUntil: "Levering tot",
      collectionNoEarlierThanHelp: "De ophaaldatum moet minstens 24 uur vanaf vandaag zijn",
      availabilityDescription: "Hoe langer de beschikbaarheidsperiode, hoe sneller we een chauffeur voor u vinden",
      addContact: "Contact toevoegen",
      cancel: "Annuleren",
      addNewContact: "Nieuw contact toevoegen",
      selectContact: "Contact selecteren",
      commentsDriver: "Opmerking voor de chauffeur",
      myRoutes: "Mijn routes",
      verifyEmail: "E-mailverificatie",
      depannage_type: "Type pechbijstand",
      depannage: [
        { name: "Mechanisch", icon: "Wrench" },
        { name: "Brandstof", icon: "Fuel" },
        { name: "Elektrisch", icon: "PlugZap" },
        { name: "Leging", icon: "Droplets" }
      ],
      description1: "Of u nu een particulier of een bedrijf bent, AMSTRAM biedt een voertuigtransportoplossing op maat van uw behoeften.",
      ownerContact: "Contact eigenaar",
      departure: "Vertrek",
      arrival: "Aankomst",
      availability: "Beschikbaarheid",
      vehicleDetails: "Voertuigdetails",
      price: "Prijs",
      status: "Status",
      type: "Type",
      make: "Merk",
      licensePlate: "Nummerplaat",
      capacity: "Capaciteit",
      transmission: "Transmissie",
      payNow: "NU BETALEN",
      paymentSuccess: "Betaling succesvol voltooid",
      loading: "Route-informatie laden...",
      detail: "Details bekijken",
      calculatingPrice: "Bezig met berekenen...",
      calculatingPriceMessage: "We berekenen de beste prijs voor uw rit.",
      phoneVerification: "Telefoonverificatie",
      titleVerified: "Nummer geverifieerd",
      enterCode: "Voer de code in die u per SMS heeft ontvangen",
      sendCode: "Code versturen",
      verifyNumber: "Nummer verifiëren",
      verifyCode: "Code verifiëren",
      smsSentTo: "SMS verzonden naar",
      resendCode: "Code opnieuw versturen",
      phoneNumberFormat: "Het telefoonnummer moet beginnen met +.",
      invalidPhoneNumber: "Ongeldig telefoonnummer, probeer het opnieuw",
      phoneUpdateError: "Fout bij het bijwerken van het telefoonnummer, probeer het opnieuw",
      incorrectCodeError: "Ongeldige code, probeer het opnieuw",
      verificationError: "Fout bij het verifiëren van het telefoonnummer, probeer het opnieuw",
      enterMakeAndModel: "Voer merk en model in...",
      enterNumberPlate: "AA-123-AA",
      seats: "plaatsen",
      enterAdditionalComments: "Voer bijkomende opmerkingen in...",
      manual: "Handmatig",
      automatic: "Automatisch",
      "semi-automatic": "Halfautomatisch",
      cvt: "CVT (Continu Variabele Transmissie)",
      valid: "Valideren",
    },
  
    // Polonais
    pl: {
      welcome: "Witamy",
      login: "Zaloguj się",
      board: "Panel sterowania",
      logout: "Wyloguj się",
      optional: "Opcjonalnie",
      service: "Usługa",
      selectService: "Wybierz swoją usługę",
      chooseService: "Wybierz usługę",
      totalPrice: "Całkowity koszt",
      Convoyage: {
        name: "Transport",
        title: "Twój pojazd, nasza trasa",
        description: "Transport z punktu A → punkt B w całej Francji i Europie, zapewniany przez profesjonalnego kierowcę dla bezpiecznej i niezawodnej obsługi."
      },
      Remorquage: {
        name: "Holowanie",
        title: "Twój pojazd, nasza trasa",
        description: "Bezpieczny transport Twojego pojazdu do warsztatu partnerskiego lub na wybrany adres."
      },
      Dépannage: {
        name: "Pomoc drogowa",
        title: "Twój pojazd, nasza trasa",
        description: [
          "Pomoc na miejscu: Szybka interwencja w przypadku częstych awarii mechanicznych.",
          "Pomoc paliwowa: Dostawa paliwa na miejsce w przypadku braku paliwa.",
          "Pomoc elektryczna: Natychmiastowa pomoc z boosterem akumulatora lub przenośną stacją EV dla pojazdów elektrycznych."
        ]
      },
      subtitle: "Usługa transportu pojazdów na miarę",
      why_choose_us: "Dlaczego nas wybrać?",
      reserve: "Zarezerwuj",
      offersTitle: "Nasze oferty",
      deliveryDescription: "Dostawa na miarę w całej Europie",
      flexibility: "Maksymalna elastyczność",
      flexibilityDescription: "Dostosowane do każdej podróży. Dostosowujemy nasze usługi do Twoich konkretnych potrzeb, czy to dla typu pojazdu, czasu lub specjalnych wymagań.",
      security: "Gwarantowane bezpieczeństwo",
      securityDescription: "Doświadczeni kierowcy i odpowiednie pojazdy. Nasi profesjonaliści są przeszkoleni do obsługi wszystkich typów pojazdów, a nasza flota jest wyposażona w najnowsze technologie bezpieczeństwa.",
      qualityPrice: "Niedościgniony stosunek jakości do ceny",
      qualityPriceDescription: "Konkurencyjne stawki za usługę premium. Oferujemy pełną przejrzystość naszych cen, bez ukrytych opłat, przy zachowaniu wyjątkowego poziomu usług.",
      peaceOfMind: "Całkowity spokój",
      peaceOfMindDescription: "Odroczona płatność, płacisz dopiero gdy Twój pojazd dotrze do miejsca docelowego. Ta polityka płatności zapewnia spokój ducha przez cały proces dostawy.",
      departLocation: "Miejsce wyjazdu (Francja)",
      arrivalLocation: "Miejsca przyjazdu",
      vehicleType: "Typ pojazdu",
      citadine: "Auto miejskie",
      moto: "Motocykl",
      camion: "Ciężarówka",
      comment: "Komentarz",
      contact: "Kontakt",
      needMorePreciseAddress: "Potrzebny bardziej precyzyjny adres, z ulicą.",
      vehicleTypes: ['Motocykl', 'Auto miejskie', 'Sportowy', 'Sedan', 'SUV', 'Van', 'Ciężarówka (<3.5t)', 'Ciężarówka (>3.5t)'],
      vehicle: "Pojazd",
      makeAndModel: "Marka i model",
      numberPlate: "Tablice rejestracyjne",
      seatingCapacity: "Pojemność miejsc",
      gearbox: "Skrzynia biegów",
      piloteExpress: {
        title: "1. Kierowca Ekspresowy",
        description: "Profesjonalny kierowca przejmuje kierownicę Twojego pojazdu dla bezpośredniej dostawy. Idealny dla szybkiej i spersonalizowanej dostawy.",
        features: [
          "Dostawa od drzwi do drzwi",
          "Doświadczeni i certyfikowani kierowcy"
        ]
      },
      coconRoulant: {
        title: "2. Toczący się Kokon",
        description: "Twój pojazd podróżuje wygodnie w specjalistycznej ciężarówce, zachowując przebieg i stan. Idealny dla luksusowych lub kolekcjonerskich pojazdów.",
        features: [
          "Maksymalna ochrona przed żywiołami",
          "Możliwy transport wielu pojazdów"
        ]
      },
      card1Title: "Maksymalna elastyczność",
      card1Description: "Dostosowane do każdej podróży. Dostosowujemy nasze usługi do Twoich konkretnych potrzeb, czy to dla typu pojazdu, czasu lub specjalnych wymagań.",
      card2Title: "Gwarantowane bezpieczeństwo",
      card2Description: "Doświadczeni kierowcy i odpowiednie pojazdy. Nasi profesjonaliści są przeszkoleni do obsługi wszystkich typów pojazdów, a nasza flota jest wyposażona w najnowsze technologie bezpieczeństwa.",
      card3Title: "Niedościgniony stosunek jakości do ceny",
      card3Description: "Konkurencyjne stawki za usługę premium. Oferujemy pełną przejrzystość naszych cen, bez ukrytych opłat, przy zachowaniu wyjątkowego poziomu usług.",
      card4Title: "Całkowity spokój",
      card4Description: "Odroczona płatność, płacisz dopiero gdy Twój pojazd dotrze do miejsca docelowego. Ta polityka płatności zapewnia spokój ducha przez cały proces dostawy.",
      footer: "Zaufaj AMSTRAM w transporcie swojego pojazdu i ciesz się doświadczeniem dostawy jak żadne inne!",
      terms: "Warunki i zasady",
      privacy: "Polityka prywatności",
      phone: "Telefon",
      telephone: "Telefon",
      phoneNumber: "Numer telefonu zaczyna się od + (+337 lub +336)",
      enterPhoneNumber: "Wprowadź swój numer telefonu",
      vehiculeAvailability: "Dostępność pojazdu",
      collectionNoEarlierThan: "Odbiór nie wcześniej niż",
      deliveryUntilHelp: "Data odbioru musi być co najmniej 3 dni po dacie zbiórki",
      deliveryUntil: "Dostawa do",
      collectionNoEarlierThanHelp: "Data odbioru musi być co najmniej 24 godziny od dziś",
      availabilityDescription: "Im dłuższy okres dostępności, tym szybciej znajdziemy dla Ciebie kierowcę",
      addContact: "Dodaj kontakt",
      cancel: "Anuluj",
      addNewContact: "Dodaj nowy kontakt",
      selectContact: "Wybierz kontakt",
      commentsDriver: "Komentarz dla kierowcy",
      myRoutes: "Moje trasy",
      verifyEmail: "Weryfikacja e-mail",
      depannage_type: "Typ pomocy drogowej",
      depannage: [
        { name: "Mechaniczna", icon: "Wrench" },
        { name: "Paliwo", icon: "Fuel" },
        { name: "Elektryczna", icon: "PlugZap" },
        { name: "Opróżnianie", icon: "Droplets" }
      ],
      description1: "Niezależnie od tego, czy jesteś osobą prywatną czy firmą, AMSTRAM oferuje rozwiązanie transportu pojazdów dostosowane do Twoich potrzeb.",
      ownerContact: "Kontakt właściciela",
      departure: "Wyjazd",
      arrival: "Przyjazd",
      availability: "Dostępność",
      vehicleDetails: "Szczegóły pojazdu",
      price: "Cena",
      status: "Status",
      type: "Typ",
      make: "Marka",
      licensePlate: "Tablica rejestracyjna",
      capacity: "Pojemność",
      transmission: "Skrzynia biegów",
      payNow: "ZAPŁAĆ TERAZ",
      paymentSuccess: "Płatność zakończona sukcesem",
      loading: "Ładowanie informacji o trasie...",
      detail: "Zobacz szczegóły",
      calculatingPrice: "Obliczanie...",
      calculatingPriceMessage: "Obliczamy najlepszą cenę dla Twojej podróży.",
      phoneVerification: "Weryfikacja telefonu",
      titleVerified: "Numer zweryfikowany",
      enterCode: "Wprowadź kod otrzymany przez SMS",
      sendCode: "Wyślij kod",
      verifyNumber: "Weryfikuj numer",
      verifyCode: "Weryfikuj kod",
      smsSentTo: "SMS wysłany do",
      resendCode: "Wyślij kod ponownie",
      phoneNumberFormat: "Numer telefonu musi zaczynać się od +.",
      invalidPhoneNumber: "Nieprawidłowy numer telefonu, spróbuj ponownie",
      phoneUpdateError: "Błąd podczas aktualizacji numeru, spróbuj ponownie",
      incorrectCodeError: "Nieprawidłowy kod, spróbuj ponownie",
      verificationError: "Błąd podczas weryfikacji numeru, spróbuj ponownie",
      enterMakeAndModel: "Wprowadź markę i model...",
      enterNumberPlate: "AA-123-AA",
      seats: "miejsc",
      enterAdditionalComments: "Wprowadź dodatkowe uwagi...",
      manual: "Manualna",
      automatic: "Automatyczna",
      "semi-automatic": "Półautomatyczna",
      cvt: "CVT (Bezstopniowa skrzynia biegów)",
      valid: "Potwierdź",
    },
    mu : {
      welcome: "Bienvenu 🇲🇺",
      login: "Konektion",
      board: "Tab debor",
      logout: "Dekonektion",
      optional: "Opsionel",
      service: "Servis",
      selectService: "Ou service",
      chooseService: "Choisissez un service",
      totalPrice: "Prix total",
      Convoyage: {
        name: "Transport",
        title: "🇲🇺 Ou loto, nou larout 🇲🇺",
        description: "Transport depi pwen A → pwen B partou dan Lafrans ek L'Europ, realise par enn profesionel pou enn transport an tout sekirite."
      },
      Remorquage: {
        name: "Remorke",
        title: "🇲🇺 Ou loto, nou larout 🇲🇺",
        description: "Transport an sekirite ou loto ziska enn garaz partenaire ou ladres ou swa."
      },
      Dépannage: {
        name: "Depanaz",
        title: "🇲🇺 Ou loto, nou larout 🇲🇺",
        description: [
          "Depanaz lor plas: Intervansion rapid pou bann pann mekanique couran.",
          "Depanaz lessans: Livrezon lessans lor plas kan ou finn fini lessans.",
          "Depanaz elektrique: Led imediat ek enn booster baterri ou enn station EV portab pou bann loto elektrik."
        ]
      },
      subtitle: "Servis transport loto lor mezir",
      why_choose_us: "Kifer swazir nou?",
      reserve: "RezerV",
      offersTitle: "Nou bann loffre",
      deliveryDescription: "Livrezon lor mezir partou dan Lerop",
      flexibility: "Flexibilite maximal",
      flexibilityDescription: "Lor mezir pou sak traze. Nou adapte nou bann servis a ou bann bezwin spesifik, ki li pou tip loto, timing ou bann demand partikilie.",
      security: "Sekirite garanti",
      securityDescription: "Sofer experimente ek loto adapte. Nou bann profesionel forme pou manipile tou tip loto, ek nou flot ekipe ek bann dernye teknolozi sekirite.",
      qualityPrice: "Kalite-pri imbatab",
      qualityPriceDescription: "Tarif konpetitif pou enn servis premium. Nou ofri enn transparans total lor nou pri, san fre kase, tou en gard an nivo servis exceptional.",
      peaceOfMind: "Trankilite total",
      peaceOfMindDescription: "Peman retarde, ou peye zis kan ou loto finn arive so destinasion. Sa politik peman la asire ou trankilite pandan tou proze livrezon.",
      departLocation: "Plas depar (Lafrans)",
      arrivalLocation: "Plas arive",
      vehicleType: "Tip loto",
      citadine: "Loto lavil",
      moto: "Moto",
      camion: "Kamion",
      comment: "Komanter",
      contact: "Kontak",
      needMorePreciseAddress: "Bizin enn ladres pli presi, ek enn lari.",
      vehicleTypes: ['Moto', 'Loto lavil', 'Loto sport', 'Berlinn', 'SUV', 'Fourgonnette', 'Kamion (<3.5t)', 'Kamion (>3.5t)'],
      vehicle: "Loto",
      makeAndModel: "Mark ek model",
      numberPlate: "Nimero plak",
      seatingCapacity: "Kapacite sez",
      gearbox: "Bwat vites",
      piloteExpress: {
        title: "1. Le Pilote Express",
        description: "Enn sofer profesionel pran volan ou loto pou enn livrezon, direk. Ideal pou enn livrezon rapid ek personalize.",
        features: [
          "Livrezon de porte-a-port",
          "Sofer experimente ek sertifie"
        ]
      },
      coconRoulant: {
        title: "2. Le Cocon Roulant",
        description: "Ou loto vwayaze konfortableman dan enn kamion specialize, prezerv so kilometre ek so leta. Parfe pou bann loto de lux ou de koleksion.",
        features: [
          "Proteksion maximal kont move tan",
          "Transport multi-loto posib"
        ]
      },
      card1Title: "Flexibilite maximal",
      card1Description: "Lor mezir pou sak traze. Nou adapte nou bann servis a ou bann bezwin spesifik, ki li pou tip loto, timing ou bann demand partikilie.",
      card2Title: "Sekirite garanti",
      card2Description: "Sofer experimente ek loto adapte. Nou bann profesionel forme pou manipile tou tip loto, ek nou flot ekipe ek bann dernye teknolozi sekirite.",
      card3Title: "Kalite-pri imbatab",
      card3Description: "Tarif konpetitif pou enn servis premium. Nou ofri enn transparans total lor nou pri, san fre kase, tou en gard an nivo servis exceptional.",
      card4Title: "Trankilite total",
      card4Description: "Peman retarde, ou peye zis kan ou loto finn arive so destinasion. Sa politik peman la asire ou trankilite pandan tou proze livrezon.",
      footer: "Fer konfians dan AMSTRAM pou transport ou loto ek viv enn lexperyans livrezon san pareit!",
      terms: "Kondision Zeneral",
      privacy: "Politik Konfidansialite",
      phone: "Telefon",
      telephone: "Telefon",
      phoneNumber: "Nimero telefon koumans par + (+337 ou +336)",
      enterPhoneNumber: "Antre ou nimero telefon",
      vehiculeAvailability: "Disponibilite loto",
      collectionNoEarlierThan: "Ramassaz pa avan",
      deliveryUntilHelp: "Dat ramassaz bizin omwin 3 zour apre dat koleksion",
      deliveryUntil: "Livrezon ziska",
      collectionNoEarlierThanHelp: "Dat ramassaz bizin omwin 24 er depi zordi",
      availabilityDescription: "Pli long peryod disponiblite, pli vit nou pou trouv enn sofer pou ou",
      addContact: "Azout kontak",
      cancel: "Anile",
      addNewContact: "Azout nouvo kontak",
      selectContact: "Swazir kontak",
      commentsDriver: "Komanter pou sofer",
      myRoutes: "Mo bann larout",
      verifyEmail: "Verifikasion imel",
      depannage_type: "Tip depanaz",
      depannage: [
        { name: "Mekanique", icon: "Wrench" },
        { name: "Lessans", icon: "Fuel" },
        { name: "Elektrik", icon: "PlugZap" },
        { name: "Vidanz", icon: "Droplets" }
      ],
      description1: "Ki ou enn individi ou enn lantrepriz, AMSTRAM ofri enn solision transpor loto adapte a ou bann bezwin.",
      ownerContact: "Kontak proprieter",
      departure: "Depar",
      arrival: "Arive",
      availability: "Disponibilite",
      vehicleDetails: "Detay loto",
      price: "Pri",
      status: "Statu",
      type: "Tip",
      make: "Mark",
      licensePlate: "Plak",
      capacity: "Kapasite",
      transmission: "Transmision",
      payNow: "PEYE ASTER",
      paymentSuccess: "Peman finn reisi",
      loading: "Pe sarz information larout...",
      detail: "Get detay",
      calculatingPrice: "Pe kalkil...",
      calculatingPriceMessage: "Nou pe kalkil meyer pri pou ou vwayaz.",
      phoneVerification: "Verifie nimero telefon",
      titleVerified: "Nimero verifie",
      enterCode: "Met kod ki to finn gagn par SMS",
      sendCode: "Avoy kod",
      verifyNumber: "Verifie nimero",
      verifyCode: "Verifie kod",
      smsSentTo: "SMS avoy lor",
      resendCode: "Avoy kod ankor",
      phoneNumberFormat: "Nimero telefon bizin komans ek +.",
      invalidPhoneNumber: "Nimero telefon pa bon, seye ankor",
      phoneUpdateError: "Ena enn problem ar mise a jour nimero, seye ankor",
      incorrectCodeError: "Kod pa bon, seye ankor",
      verificationError: "Ena enn problem ar verification nimero, seye ankor",
      enterMakeAndModel: "Mark ek model...",
      enterNumberPlate: "AA-123-AA",
      seats: "Nombre plas",
      enterAdditionalComments: "Met un komanter siplemanter...",
      manual: "Manyel",
      automatic: "Otomatik",
      "semi-automatic": "Semi-otomatik",
      cvt: "CVT (Transmisyon variabl kontini)",
      valid: "Konfirme",
    }
  };


const intStatus : { [key: number]: string } = {
  0: "À traiter",
  1: "Accepter",
  2: "Annuler",
  3: "Completer"
} 

export { contenu , intStatus};